### ISSUE TITLE
Riesen Fehler im Array!!1!

### ISSUE THREAD

**Issue by theoroiroi** [3ahmns-WiSem-2223/12prosenstatter-fingeruebung-eindimensionalesArray#1]
Lieber Paul,
ich habe dein Skript sehr genossen, doch leider ist mir ein kleiner, aber sehr starker Fehler aufgefallen.
Du hast... zu viele nicht verwendete Namespaces.

Mit freundlichen Grüßen,
dein Theo

**Comment by PRosenstatter** [comment]
Sehr geehrter Herr Roider

ich danke dir für den Hinweis

Mit freundlichen Grüßen 
Baule
